name: buf

on:
  push:
    branches: [main]
  pull_request:

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          lint: true
          format: true
          breaking: true
          breaking_against: "https://github.com/FoldForge/proto.git#branch=main,ref=HEAD~1"
